- solver_greedy_max.py
Python is complaining about `time_support()` before an `import` in `solver_greedy_max`.
> Removing warnings.

- greedy_max/__init__.py
- greedy_max/plan.py
- greedy_max/schedule.py
- greedy_max/utils.py
- resource_mock/__init__.py
- solver_greedy_max.py
This PR contains both SCHED 30 and 29.
- On the Resource Mock:
- There was an error at reading the excel file that caused missing information
-  Information of missing dates is retrieve from the nearest date before the asking one 
- On the Naming convention:
- The `Scheduling Unit` class was renamed `Visit` in according with the correct definition.
> Sched 30-29: Fix missing information in Resource and change naming convention to Visit

- collector/__init__.py
_process_observation_data was overwriting the target_name with the target group name.  This fixes that.
> Fixed bug with setting target name

- common/api/__init__.py
The general abstract API for mini-model population, which consists simply of static abstract functions to be implemented to populate the various elements of the mini-model. The concrete implementations (there will be one for OCS, and one for GPP, and both will receive `dict`s based on JSON objects, either provided by the ODB program extractor or the GPP GraphQL queries) will need to be written.
It is possible that some logic will end up being needed here, but since the implementations are so different, we leave it as this for now.
> SCHED-73: General API for mini-model population.

- download_programs.py
Since in the initial implementation to get the Scheduler to run end-to-end, we will not be using GraphQL services, we need access to the programs in the Scheduler observing database (ODB).
This script queries the Scheduler ODB for a list of the programs it contains, filters the programs of interest, retrieves them, and then zips them into a zip file for future use.
> SCHED-83: Downloading script for ODB programs

- api/ocs/__init__.py
- common/minimodel/__init__.py
- data/GN-2022A-Q-999.json
- tests/test_ocs_api.py
This PR is to serve as the base of a test case for the OCS API and the mini-model.
Right now it:
1. Adds a very basic program that tests the majority of the mini-model data structures, i.e. GN-2022A-Q-999
2. Adds the start of a test case to check that the API produces what we expect, in `test_ocs_api.py`
3. Fixes some small bugs in the API and mini-model.
What remains to be done is the rest of the implementation of `create_minimodel_program()` in `test_ocs_api.py`, which will be delegated to @stroncod 
Note that this PR requires `pytest` to be installed to run:
`pip install pytest`
Then `pytest` can be run on `test_ocs_api.py` and if it passes after the rest of the function is implemented, we have the results we expect.
> SCHED-85: Start of test case for basic bare bones program

- collector/__init__.py
- common/minimodel/__init__.py
Migration of old Collector's weather variant mock fetching to simulate for the Env service and OCS historical data.
Implementation of `Variant` class in mini-model to represent weather variants.
@bryanmiller, could you shed some light on this?
There are more variants in the old Collector, but they are not formatted properly with regards to units. 
I am not sure what:
```
wdir = -1
```
is supposed to indicate. (Is it -180 degrees?)
Also, the `time_blocks` are not used at all. What are these supposed to mean? Is it the block for which a conditions variant is active?
> SCHED-96: Variant implementation.

- collector/__init__.py
- common/output/__init__.py
- common/scheduler/__init__.py
- selector/__init__.py
This is a small PR to add some more information to the `Collector` to facilitate retrieval, largely concerning observation IDs and observations.
Also added are accessors to the private data in the `Collector` so that we no longer have to unpythonically violate the private nature of fields to get its contents and calculated output.
For some reason, some harmless Scheduler crap ended up in here. Ignoring it.
> SCHED-108: Additional Collector fields and accessors

- common/minimodel/__init__.py
- components/collector/__init__.py
- components/selector/__init__.py
- scripts/run_scheduler.py
Make everything available through the `Selector` so that we don't have to get certain things from the `Collector` and the `Selector`. The previous `Collector` methods are now accessed through the `Selector` and the base target information retrieval has been moved to the mini-model for simplicity so you can get an `Observation`'s base `Target` directly from the `Observation` instead of going through the `Collector`.
> SCHED-126: Interface simplification.

- api/programprovider/ocs/__init__.py
- common/minimodel/resource.py
- components/collector/__init__.py
- components/selector/__init__.py
- scripts/run_scheduler.py
1. Made `Resource` not accept `id` of `None` or equivalent of `None`.
2. Fixed `Atom` parsing code to not return FPUs and filters that are the equivalent of `None`.
3. `Collector` now makes sure `Resource` needs are all met.
4. `schedulable_slot_indices` now takes `night_idx` properly into account.
> SCHED-144: Bugfixes

- api/programprovider/ocs/__init__.py
- common/calculations/nightevents.py
- common/minimodel/constraints.py
- common/minimodel/plan.py
- common/output/__init__.py
- common/sky/events.py
- common/sky/moon.py
- common/sky/test/test_events.py
- common/types/__init__.py
- components/collector/__init__.py
- components/ranker/__init__.py
- environment.yml
- scripts/export_atoms.py
- scripts/run_scheduler.py
This fixes several things:
- Some of the typehints in the `Plans` code was incorrect.
- The `sky` library was not using `Moon.time_by_altitude` on moon set, so a triple was returned instead of the correct value.
- Times were not being wrapped correctly in `AstroPy``Time` and `TimeDelta` objects. This led them to have type `Quantity` instead of `Time` or `TimeDelta`, which was causing problems.
- Fix (possibly temporary) for FPUs that have a value of `None` during atom extraction.
- Remove tqdm, add Django (for now for GraphQL).
- Output fixes and commenting out uninformative logging info.
> HOTFIX: Fixing time information, type hints, calculations, and cleaning output

- api/observatory/abstract/__init__.py
- api/observatory/gemini/__init__.py
We add to `ObservatoryProperties`:
1. `is_instrument`: determine if a `Resource` is an instrument.
2. `acquistion_time`: a lookup for acquisition time given an instrument and an `ObservationMode`.
Concrete implementations of these classes in `GeminiProperties`.
> SCHED-172: Add properties to ObservatoryProperties for instrument calculations

- mock/environment/__init__.py
- scripts/weather_experiment.py
There was a small bug in the initial code wherein the first line for each date was missing.
This fixes that issue and simplifies the logic of dividing into dates: when a new date is found, it makes sure that the first entries for `cc_band` and `iq_band` are defined so we can use `fillna` later to fill in the missing entries.
> SCHED-179: Bugfix in missing first row for each date and simplification.

- mock/resource/__init__.py
- mock/resource/test/test_resource_mock.py
Beforehand, in `ResourceMock`, if `Resource` information was requested for a date that was past the last date for which `Resource` data existed, we would return the `Resource` information for the last date for which it was designed.
As per conversation with Bryan yesterday, we should instead return an empty set. This should not be a problem in practice because while the files containing FPU information and grating information may extend past the last date in the files (in which case asking for a date just after the last entry should return the last `Resources` as defined in those files), the Excel spreadsheet containing telescope configuration information has an entry for each valid date, so it will be guaranteed that data will exist for the entire range of dates.
> SCHED-243: Resources past last date in ResourceMock

- app/core/components/collector/__init__.py
- app/core/components/collector/test/test_clear_observation_info.py
Beforehand, for a list of programs, we cleared out the observation used program and partner time too late in the code, i.e. after calling `Collector._calculate_target_info`. Since this method uses the `Observation.total_time` method, the observation times must be cleared before the target info is calculated.
Now, instead of taking the list of `Program` and processing it, we simply iterate over the `Observation`s as they are read in and zero the `program_used` and `partner_used` in the component `Atom`s.
> SCHED-253: Changed logic to zero out observation times and move it earlier in code for res_visibility_time.

- app/core/components/collector/__init__.py
This fixes a big with regards to elevation constraints for an observation.
**NOTE:** This should NOT be merged until Monday's tech meet to discuss a more thorough plan. This is the minimal change that can be made.
@stroncod This dramatically changes the plan output from the DummyOptimizer from:
```
+++++ NIGHT 1 +++++
Plan for site: GN
2018-09-30 19:59:00.000017-09:00   GN-2018B-Q-104-11
2018-09-30 19:59:00.000017-09:00   GN-2018B-Q-104-7
2018-09-30 19:59:00.000017-09:00   GN-2018B-Q-104-10
2018-09-30 19:59:00.000017-09:00   GN-2018B-Q-104-12
Plan for site: GS
```
to:
````
+++++ NIGHT 1 +++++
Plan for site: GN
2018-09-30 19:59:00.000017-09:00   GN-2018B-Q-101-1393
2018-09-30 19:59:00.000017-09:00   GN-2018B-Q-101-1455
2018-09-30 19:59:00.000017-09:00   GN-2018B-Q-104-11
2018-09-30 …
```
> SCHED-254: Bug fix for elevation.

- app/core/components/collector/__init__.py
- app/core/scheduler/modes.py
Because we are not using the new Builder class yet in GreedyMax, this is a hack that needs to be reverted to automatically assume `ValidationMode` and clear all obs times for the requires obs classes.
> HACK: Forcing zeroing out of observation times.

- app/config.py
- app/core/builder/blueprint.py
- app/core/builder/builder.py
- app/core/calculations/targetinfo.py
- app/core/components/collector/__init__.py
- app/core/components/selector/__init__.py
- app/core/programprovider/abstract/__init__.py
- app/core/programprovider/ocs/__init__.py
- app/core/programprovider/ocs/test/test_ocs_api.py
- app/core/scheduler/scheduler.py
- app/core/scheduler/test/test_clear_observation_info.py
- scripts/export_atoms.py
- scripts/run_scheduler.py
Now, to the `Collector.load_programs` method, we pass a subclass of `ProgramProvider` instead of an instance.
This is done because the filtering on `Observation`s based on `ObservationClass` has to happen during the parsing of the JSON data instead of in the `Collector`: otherwise, we import all `Observation`s regardless of `ObservationClass`. This was causing `AndGroup`s to contain acquisitions and calibrations, and then when we did the filtering in `load_program`s, we would end up filtering out scheduling groups that contained any acquisitions or calibrations as a result since those `Observation`s were in the scheduling groups.
Now, `load_programs` instantiates the instance of `ProgramProvider` passed to it, giving it the `obs_classes` parameter that is part of the `Collector` …
> SCHED-268: Major architectural changes to allow filtering on ObservationClasses in ProgramProviders and bug fixes

- app/core/components/collector/__init__.py
- mock/resource/__init__.py
- mock/resource/test/test_resource_mock.py
As per our discussion at the Scheduler meeting yesterday, this is a fix to use UTC dates to obtain Resource information from the mock, by chopping the datetime to a date and then subtracting one to get the correct date.
I accidentally committed these changes as SCHED-255, which is a UI issue.
> SCHED-258: Update interface with ResourceMock to use UTC dates

- app/core/programprovider/ocs/__init__.py
- app/core/programprovider/ocs/test/test_ocs_filtering.py
- app/core/scheduler/test/test_clear_observation_info.py
Before, we were not filtering on the `active` status of `Observation`s when we were parsing in the `OcsProgramProvider`.
As a result, some inactive `Observation`s were making their way into the `Program`, and when the `Selector` was generating the `Selection`, these inactive `Observation`s were preventing certain scheduling `Group`s from being included  in the `Selection`.
This change now filters out based on the `active` property of `Observation`s.
> SCHED-273: OcsProgramProvider now filters on active status.

- app/core/calculations/selection.py
- app/core/components/selector/__init__.py
- app/core/programprovider/abstract/__init__.py
- app/core/programprovider/ocs/__init__.py
- app/core/programprovider/ocs/test/test_ocs_api.py
1. The `ProgramProvider` and `OcsProgramProvider` now both pass `program_id` to the `parse_xxx_group` methods since lucupy has changed to have a `program_id` field in `Group`.
2. The `Selector.get_group_info` method now takes a `UniqueGroupID` instead of `GroupID` since the `GroupID`s were not unique and scheduling groups were overwriting each other in the dictionary this manages.
3. The `Selection.show_groups()` method now displays, for each program, the `UniqueGroupID` rather than the `GroupID`.
4. Test cases fixed.
> SCHED-277: Populate Groups with program_id and change some structures to use UniqueGroupID

- app/app.py
This blocks outside request to the Scheduler and satisfies the FrontEnd server requirements.
> SCHED-285: Add CORS Middleware to FastAPI

- .github/dependabot.yml
- scheduler/db/dbmanager.py
- scheduler/db/planmanager.py
- scheduler/graphql_mid/schema.py
- tests/unit/scheduler/graphql_mid/__init__.py
- tests/unit/scheduler/graphql_mid/test_graphql_mutations.py
- tests/unit/scheduler/graphql_mid/test_graphql_queries.py
There were some errors when the DB was not initialize but it was query anyway, making the instance in Heroku useless, causing problems on the UI as well. This fix these and add testing to our endpoints so we can check if any changes break them.
> SCHED 297: GraphQL error handling with shelve 

- scheduler/core/components/optimizer/dummy.py
- scheduler/core/components/optimizer/greedymax.py
- scheduler/core/plans/__init__.py
Instead of `Plan.has`, we use `__contains__`.
Instead of doing:
```python
plan.has(obs)
```
or
```python
not plan.has(obs)
```
we can now do:
```python
obs in plan
```
and
```python
obs not in plan
```
> SCHED-331: Removed has method, replaced with __contains__.

- scheduler/services/horizons/__init__.py
- tests/unit/scheduler/external/horizons/test_horizons_client.py
This fixes the test case that is causing all PRs to fail the test case check.
It also includes some changes to the HORIZONS code for immutability, and makes `HorizonsAngle`, the convenience collection of angle transformations that are static, an uninstantiable class.
More importantly, it also adds a `Coordinates` generator for hypothesis. The former generation was generating values in degrees when `Coordinates` and the many methods it calls require the units to be in radians.
> SCHED-329: Fix test cases and HORIZONS code

- scheduler/core/components/optimizer/__init__.py
- scheduler/core/components/optimizer/greedymax.py
- scheduler/core/components/optimizer/timeline.py
- scheduler/core/plans/__init__.py
- scheduler/scripts/run_greedymax.py
This includes the initial use of timelines (array of time slots) for determining the open intervals to schedule and track scheduled observation ids.
A new behavior is that it will search all available intervals, not just the first, for the max scoring observation.
It can also preferentially choose groups that don't need to be split as long as the score is high enough (within a fraction of the top-scoring group).
> Gmax refactor - timelines

- scheduler/core/calculations/programinfo.py
- scheduler/core/components/ranker/base.py
- scheduler/core/components/ranker/default.py
- scheduler/core/components/selector/__init__.py
The `Ranker` should not be scoring all `Observation`s across all `Program`s upon creation.
Since we may create several `Ranker`s simply out of convenience (we should decide if the `Ranker` is owned by anything, e.g. possibly the `Selector`), and in subsequent scoring of `Program`s after `Observation`s or `Atom`s are executed, we do not want to use the `Collector`'s cache of `Program`s, but the modified `Program`s after GreedyMax produces a `Plan` and part of it is executed.
Formerly as well, `Observation`s that belong to observation groups were being scored, but the scoring was useless since we were lacking some information necessary to score the observation group containing the `Observation`, such as the `Conditions` / `Constraints` (see GN-2018B-Q-101-1460 and GN-2018B-Q-101-1462 in the …
> SCHED-351: Ranker modifications

- scheduler/core/components/optimizer/greedymax.py
- scheduler/core/components/optimizer/timeline.py
The timelines (time slots) are used to write the visits in the output plans in chronological order.
> SCHED-357: visits in output plans in chronological order

- scheduler/core/calculations/selection.py
- scheduler/core/components/selector/__init__.py
- scheduler/scripts/check_headers.py
- scheduler/scripts/run_scheduler.py
This adds a method to the `Selection` that allows the re-scoring of `Program`s. This simply defers to the `Selector` but without revealing the entire `Selector` to the `Selection`.
A call to rescore a program results in a `ProgramCalculation`, which contains all the data used by the `Selector` to assemble the `Selection`.
> SCHED-362: Ability to re-score programs from the Selection

- scheduler/core/components/optimizer/greedymax.py
- scheduler/core/components/selector/__init__.py
This fixes an issue in the `Selector` where when a `select` was run, too many things were copied.
This ended up with things in the `Selection` no longer being linked, e.g. a `Group` in the `Selection` would not be linked to the `Program` from which it originated, and thus making any changes to the `Group` would not percolate up to the `Program` level. Similarly, this was a problem with `Observation`s and the `Group` to which they belonged.
Now,, they should be working correctly and the members of a `Selection` should now have their appropriate relationships maintained.
> SCHED-374: Fixed copying issues.

- scheduler/core/programprovider/abstract/__init__.py
- scheduler/core/programprovider/ocs/__init__.py
This just tidies up a bit of code that was changed in the `OcsProgramProvider` to detect if an `Observation` is splittable, and since parameters were added to methods in the class, the parameters were propagated up to `ProgramProvider`.
> SCHED-449: Slight cleanup of OcsProgramProvider.

- scheduler/core/calculations/groupinfo.py
- scheduler/core/components/optimizer/greedymax.py
- scheduler/core/programprovider/ocs/__init__.py
- scheduler/services/resource/base.py
- tests/unit/scheduler/core/programprovider/ocs/test_ocs_api.py
Some minor improvements and cleanup to:
1. Move magic values out of a method.
2. Use f-strings to create a barcode.
3. `ResourceService._mdf_to_barcode` now properly reuses cached `Resource`s that have already been created instead of making duplicates of existing ones.
This also fixes a test case that broke as a result of the addition of the `obs_mode: ObservationMode` field to `Atom` in lucupy.
> SCHED-451: Cleanup and fixing test cases

- demo/try_scheduler.ipynb
- scheduler/core/components/collector/__init__.py
- scheduler/core/components/selector/__init__.py
- scheduler/scripts/run_greedymax.py
- scheduler/scripts/run_greedymax_twice.py
It turns out that in the `Selector.selection` method, `ALL_SITES` was always being used, which was causing errors since if only one site was given to the `Collector` unless the `NightEvent` information for the nights desired had already been computed and cached in `NightEventsManager`, we had observations being evaluated using information that didn't exist in `NightEventsManager` against env data, which generated numpy broadcast errors in the size of arrays.
Note that this also adds a script that can be run to test to make sure things work now (`run_greedymax_twice.py`) so as to run the same scenario that was originally discovered by German in Mercury without all the additional noise Mercury generates.
There is also some error-handling code added, and the scripts `run_greedymax.py` and …
> SCHED-454: Fixed issue where illegal numpy broadcasts were being done.

- scheduler/core/components/nighteventsmanager/__init__.py
- scheduler/scripts/run_greedymax_twice.py
The former caching was not working correctly.
The actual `NightEvents` calculations are quite quick, at less than one second a day on my local machine, but they are requested many times, leading to timing issues.
Now, instead of trying to reuse parts of dates already calculated and cached, we simply create an ID for the current request (which may overlap or even be a subset of previous requests), calculate that, and cache that.
This is far simpler because the `NightEvents` for multiple nights are stored in a single `NightEvents` object, so to manage multiple `NightEvents` objects and then extract and merge parts of them is very difficult. Given the low calculation time, this does not seem necessary.
> SCHED-463: Fixed NightEventManager caching.

- scheduler/core/components/optimizer/greedymax.py
This avoids a crash but we need to investigate why it was getting to this state (selector issue?) and may need to add other error checks.
> Quick fix to avoid referencing past the end of the list

- demo/try_scheduler.ipynb
- scheduler/core/components/collector/__init__.py
- scheduler/core/output/__init__.py
- scheduler/core/statscalculator/__init__.py
- scheduler/scripts/run_greedymax.py
- scheduler/scripts/run_greedymax_twice.py
This addresses multiple tasks:
* GSCHED-471: Remove time fields from Validation mode UI
* GSCHED-472: Add a number of nights field to the Validation UI
* GSCHED-473: Output actual dates in Validation UI instead of day indices
* GSCHED-478: Change dates in Validation UI to match actual nights
* GSCHED-479: Remove end date from Validation UI and instead add field for num nights visibility calc
* GSCHED-480: Fix Collector to allow visibility calculations for one night
> SCHED-471: UI changes and improvements for Validation Mode

- scheduler/core/components/optimizer/greedymax.py
This fixes some bugs in the greedymax internal time accounting. Unused partner_cal (telluric) observations are set to Inactive, avoiding errors during rescoring. Any group added to a plan is removed from group_data_list so that it won't be scheduled again. This is a simple way to avoid multiple visits of an observation on a single night.
> Fixes to internal time accounting, avoid multiple visits on one night

- scheduler/core/calculations/selection.py
- scheduler/core/components/selector/__init__.py
- scheduler/core/types/__init__.py
Now we allow a map to be specified from `NightIndex` to `TimeslotIndex` that zeroes out the scores prior to the specified `TimeslotIndex` for the night to allow for partial scoring.
Anything with a score of 0 should not be scheduled, so this allows us to in essence say that we have scored up to that point in the night and subsequent plans should be empty for that portion of the night.
> GSCHED-482: Modify scoring algorithms to allow for partial night scoring.

- scheduler/core/calculations/selection.py
- scheduler/core/components/selector/__init__.py
- scheduler/core/types/__init__.py
- scheduler/scripts/run_greedymax.py
This PR:
* Simplifies some function calls for scoring programs by removing parameters that should be set.
* Fixes calls from GreedyMax to use the starting time slots instead of starting back at time slot 0.
* Changes the structure of the lookup for starting time slots.
> SCHED-428B: Fixes and restructuring for starting time slots.

- scheduler/core/components/collector/__init__.py
- scheduler/core/components/selector/__init__.py
- scheduler/scripts/run_greedymax.py
- scheduler/scripts/run_greedymax_twice.py
Time accounting can now be done for specified sites for partial nights, up to (excluding) a specified time slot for each night.
If an event occurs at time `t` for Site `s`, then calling:
```
collector.time_accounting(plans, sites=frozenset({s}), end_timeslot_bounds={s: t})
```
will only perform time accounting for visits in the plan for site `s` up until timeslot `t`.
Then it will be possible to perform another selection for the site starting at timeslot `t` (when the event occurred) and run the optimizer from that point.
All previous timeslots will be unused: the scores for the observations at site `s` will be set to `0` for all timeslots prior to `t`, which means nothing will be scheduled for them in the plan.
This allows us to make partial plans of decreasing length from different …
> SCHED-491: Time accounting can now be done for partial nights.

- scheduler/core/output/__init__.py
Due to the fact that `Visit`s seem to be overlapping in `Plan`s, I am adding extra output about the end time and number of time slots for each `Visit` to the output, and adding a header row to the table along with extra spacing to make the data easier to read.
> SCHED-495: Improve plan output

- scheduler/core/builder/__init__.py
- scheduler/core/builder/modes.py
- scheduler/core/calculations/groupinfo.py
- scheduler/core/calculations/scores.py
- scheduler/core/calculations/selection.py
- scheduler/core/calculations/targetinfo.py
- scheduler/core/components/base/__init__.py
- scheduler/core/components/optimizer/__init__.py
- scheduler/core/components/optimizer/base.py
- scheduler/core/components/optimizer/greedymax.py
- scheduler/core/components/optimizer/timeline.py
- scheduler/core/components/ranker/__init__.py
- scheduler/core/components/ranker/default.py
- scheduler/core/components/selector/__init__.py
- scheduler/core/service/service.py
- scheduler/db/dbmanager.py
- scheduler/db/planmanager.py
- scheduler/graphql_mid/inputs.py
Necessary fix to `RankerParameters` for Python 3.12 and the elimination of several warnings.
> SCHED-497: Cleanup for Py3.12 migration.

- requirements.txt
- scheduler/core/eventsqueue/__init__.py
- scheduler/core/eventsqueue/event_queue.py
- scheduler/core/eventsqueue/events.py
- scheduler/scripts/run_with_events.py
This PR:
* Turns `EveningTwilight` into a bonafide event. Without it, a night will not be scheduled.
* Uses a wrapper around a `SortedList` to manage the events for a given night index for a given site.
* Removes the redundancy of doing an initial `Selection` and then a `Selection` for each event: since `EveningTwilight` is now a full class `Event`, it is expected to be the first `Event` of a night for a site: it will set the starting time for the night so that the time slots can be calculated from the other `Event`s that occur. If `EveningTwilight` is missing, we cannot calculate time slots for other `Event`s for a night and the code fails.
* `Event`s have been marked either `ABC` or `@final`.
* `Event`s now have a method to calculate the time slot in which they occur.
* Removes …
> SCHED-503B: Event handling cleanup

- scheduler/core/components/selector/__init__.py
- scheduler/core/programprovider/ocs/__init__.py
- tests/unit/scheduler/core/programprovider/ocs/test_ocs_api.py
The only observations that are parsed from the JSON code in the OCS program parser are those that are:
* `READY`
* `ONGOING`
* `OBSERVED`
We want the latter since we reset all observations after they have been read into the `Collector`. Since this is past semester data, most (if not all) observations will be marked `OBSERVED`.
The `Selector` code now ignores `INACTIVE` and `OBSERVED` observations (we will be flipping some observations to INACTIVE based on program splitting with unnecessary tellurics, for example), and the `Selection` only contains `READY` and `ONGOING` observations.
This generates a slightly different plan as expected since certain observations that were formerly admitted but should not have been are now properly excluded.
> SCHED-486: Observations marked ON_HOLD or PHASE2 are no longer included

- scheduler/core/components/optimizer/greedymax.py
- scheduler/core/output/__init__.py
- scheduler/core/programprovider/ocs/__init__.py
Fixes a bug in _add_visit for how the cumulative sequence length is compared with the total observation length. This fixes the overlap between visits.
Also, this prevents NIR spectroscopic observations from being split. 
Finally, there are a few bug fixes related to using index numbers vs slices.
> Fix overlapping visit bug

- requirements.txt
New version of lucupy does not work with Validation mode.
> SCHED-528: Fixing requirements.txt for validation.

- definitions.py
- scheduler/core/components/collector/__init__.py
- scheduler/scripts/run_greedymax.py
Here is the next iteration of collector time accounting. It still needs some tweaking but it would be good to test what is here
- don't charge scheduling groups if an event occurs during the group visit (TODO: just do this if there is more than one observation in the group)
- observation not in a scheduling group will charge the atoms up to an interrupting event
- set unneeded partner calibrations (e.g. tellurics) to INACTIVE
Other TODO: add no_charged time category and charge interrupted observations to that.
Please review and clean up, but don't remove the commented-out print statements, I may need those for the next iteration.
> GSCHED-489: updated collector time accounting

- definitions.py
- scheduler/core/components/collector/__init__.py
- scheduler/core/plans/__init__.py
This cleans up the branch SCHED-489 by:
* Fixing some bugs (e.g. `GroupVisit` class declaration, checking method `Group.is_scheduling_group` instead of invoking it).
* Simplifying and cleaning up logic.
* Reducing `Observation` comparisons to ID comparisons instead of entire `Observation` comparisons, which compare everything (except sequences, as this functionality has been temporarily suspended).
> SCHED-489 cleanup

- scheduler/core/components/collector/__init__.py
- scheduler/core/components/optimizer/dummy.py
- scheduler/core/components/optimizer/greedymax.py
- scheduler/core/eventsqueue/events.py
- scheduler/core/plans/__init__.py
As pointed out by @stroncod, the logic to convert a time quantity to number of time slots was repeated throughout the code base. This method has no inherent tie to `Plan`, where it was included before, and the logic has been moved to lucupy and all of the implementations (and other calculations in the code that calculate this explicitly) now point there.
**NOTE:** This requires an update to lucupy 0.1.59.
> SCHED-531: Move all time to num timeslots calculations to point to lucupy time2slots

- scheduler/core/components/ranker/default.py
Since these should be settable by users, they should not be `ClassVar`, and looking forward to possible uses of future versions of Python, should be initialized by `default` but by `default_factory`.
They should also not be frozen as numpy arrays.
> SCHED-532: RankerParameters should not be ClassVars and should be initialized with default_factory.

- definitions.py
- scheduler/core/calculations/nightevents.py
- scheduler/core/components/ranker/default.py
- tests/unit/scheduler/core/collector/collector_fixture.py
- tests/unit/scheduler/core/collector/test_datetime_conversions.py
- tests/unit/scheduler/core/collector/test_proper_motion.py
Methods on `NightEvents` to convert between `NightIndex` and `TimeslotIndex` and `datetime` objects in both directions, both using UTC and localized time.
> SCHED-534: Methods to convert between time coordinates and datetimes

- definitions.py
To set logging level
1) check command line parameter
2) else look for SCHEDULER_DEBUGGING environmental variable
The latter works with Jupyter notebooks.
> Add check for environmental variable to set the logging level.

- requirements.txt
- scheduler/core/calculations/nightevents.py
- scheduler/core/components/optimizer/base.py
- scheduler/core/components/optimizer/timeline.py
- scheduler/graphql_mid/types.py
We still need pytz as a dependency for pandas, but we are no longer using it internally.
> SCHED-588: Removing pytz.

- scheduler/core/components/selector/__init__.py
- scheduler/scripts/run_main.py
Previously, we were performing group filtering using `len(indices)` when for numpy to act correctly, we should have been using `indices.size`.
We also now explicitly filter out the root group.
> SCHED-602: Fix group selection

- scheduler/config.yaml
- scheduler/core/builder/blueprint.py
- scheduler/core/builder/schedulerbuilder.py
- scheduler/core/components/optimizer/greedymax.py
- scheduler/core/components/optimizer/optimizers.py
- scheduler/core/components/selector/__init__.py
- scheduler/core/components/selector/timebuffer.py
- scheduler/core/service/service.py
- scheduler/core/sources.py
- scheduler/scripts/run_main.py
This PR focuses on several things:
1. Configuration of a `TimeBuffer` to allow programs to surpass their allocated time (by either a flat number of minutes or a percentage of the program length) in the `config.yaml` file. By default, this is configured to be 30 minutes.
3. The `Selector` now has a `SelectorBlueprint` and is created by the `Builder`.
4. The `Selector` now stores the `TimeBuffer` to use in scoring.
5. If a program is out of time (with the inclusion of the added buffer time calculated for the program via the `TimeBuffer`), we terminate its `ProgramCalculations` and return `None`.
6. GreedyMax is modified to handle `ProgramCalculations` being `None` during program re-scoring.
It requires an update to lucupy to run correctly or it will break.
It also:
1. Moves `Instantiable` …
> SCHED-605: Filter out programs that are out of time

- scheduler/core/components/collector/collector.py
avail_resources needed to be compared to the other properties over the same range of sa_idx.
> GSCHED-613: fix avail_resources array comparison

- scheduler/core/builder/validationbuilder.py
- scheduler/core/programprovider/ocs/__init__.py
- scheduler/scripts/run_greedymax.py
- scheduler/scripts/run_main.py
- scheduler/services/resource/file_based_resource_service.py
Allow import of classical programs into the collector by making them equivalent to Band 1.
Fix parsing of visitor instrument names to match the resources in the telescope calendar
Make GCAL an always available resource, which is the case. This removes a lot of warning messages but doesn't affect scheduling at this time.
> Import of classical programs, fix parsing of visitor instrument names

- tests/unit/scheduler/services/resource/test_ocs_resource_service.py
This PR broke the test cases by adding `GCAL` to the list of resources, so here we fix it by adding `GCAL` to the expected resources.
> SCHED-621: Adding GCAL to resources to fix test cases.

- scheduler/core/components/collector/collector.py
- scheduler/core/components/ranker/default.py
- scheduler/scripts/filter_demo.py
- scheduler/scripts/run_greedymax.py
- scheduler/services/resource/filters.py
Two ways of using the telescope calendar to adjust program score are implemented
- observation visibilities for a night are only included in the visfrac calculations if the program is allowed to be scheduled on the night (program_filter) 
- an extra program_priority term has been added to the ranker to allow programs with program_priority status to be given a scoring boost.
> GSCHED-616: program priorities based on telescope calendar

- scheduler/core/components/optimizer/greedymax.py
- scheduler/core/programprovider/ocs/ocsprogramprovider.py
- scheduler/services/resource/file_based_resource_service.py
GRACES sequences are non-standard so the acquisition steps have to be ignored.
Since GRACES is accessed via GMOS-N it does not appear in a Port column in the telescope calendar. We check the GRACES availability if GMOS-N is also available. (Note, use of the port columns and the instrument columns is redundant. In the future we could simplify this by just using the instrument columns for availability and adding the port as part of the configuration in case it is needed, eg. for AGS. This is low priority).
> Fix parsing GRACES sequences and calendar availability

- scheduler/core/components/changemonitor/change_monitor.py
- scheduler/core/components/selector/selector.py
- scheduler/core/eventsqueue/events.py
- scheduler/core/service/service.py
- scheduler/graphql_mid/types.py
- scheduler/scripts/run_main.py
- scheduler/services/environment/ocs_env_service.py
To increase the clarity of variable names, `VariantChange` has been renamed to `VariantSnapshot` in lucupy.
Additionally:
1. `VariantSnapshot` can now generate a `Variant` with a specified array (number of timeslots) size.
2. The `Selector` now stores a `VariantSnapshot` per site instead of having arrays for each value.
3. The `Selector` uses `VariantSnapshot.make_variant` to create the `Variant` instead of doing so by hand when scoring an `Observation`.
4. The `ChangeMonitor` uses `VariantSnapshot.make_variant` to create the `Variant` to determine if a `Visit` can be completed when a `WeatherChangeEvent` occurs.
5. The GraphQL code for `NewWeatherChange` was broken inadvertently by changes and has now been repaired.
> SCHED-653: Change to VariantSnapshot and simplify code.

- scheduler/core/components/changemonitor/change_monitor.py
- scheduler/core/plans/plans.py
- scheduler/core/service/service.py
- scheduler/scripts/run_main.py
The blocking sites collect and manage events that block a site from creating a plan.
Examples include:
* Weather closure events
* Fault reports
* Other unexpected events (e.g. TMT protests).
Until the blocking events are resolved, the relevant site is unable to be used for scheduling and simply produces empty `Plan`s.
> SCHED-630: Add blocking lists for sites to ChangeMonitor.

- scheduler/core/service/service.py
- scheduler/scripts/run_main.py
If a site is still blocked by the end of the night:
1. If there are additional events, process them (hoping to unblock the site).
2. If all of the events are processed for a night and the site is still blocked, issue a warning.
> SCHED-632: Code to unblock sites if events exist and issue warning if still blocked

- .gitignore
- scheduler/core/builder/validationbuilder.py
- scheduler/core/sources/origins.py
- scheduler/core/sources/sources.py
This code allows the OCS Resource and Env services to be pickled to increase the speed of the executing code.
The bulk of the speed increase is needed in the viscalcs, but this was a good test that `Resource` is now stable and working correctly.
The `Sources` do not load twice now as they did before, and logging is added to display whether the services are loaded from pickles or created.
Plans based on pickled services or freshly created services are the same, as expected.
> SCHED-666: Pickling OCS Resource and Env service now works.

- scheduler/core/components/collector/collector.py
This PR rearranges the `Collector`'s `load_programs` method to separate the stages of doing all three in one loop interation:
* Program parsing
* Timing window calculations
* Visibility calculations
To instead having two loops, one where we do:
* Program parsing
and a second one (with stored values for observations obtained during the parsing) - intended to be parallelized with the results cached via redis  - to instead do:
* Timing window calculations
* Visibility calculations
> SCHED-670: Rearrange Collector load_programs.

- scheduler/core/components/collector/collector.py
- scheduler/services/proper_motion/__init__.py
- scheduler/services/proper_motion/proper_motion_calculator.py
Previously, we were calculating only one set of coordinates for each night using the proper motion calculations when we should have been generating coordinates for every time slot.
This code extracts the proper motion code from the `Collector`, puts it into its own service, and accepts a `SiderealTarget`, a starting time, a number of time slots, and a time slot length, and returns an AstroPy `SkyCoord` object that contains entries for every time slot. This works with the visibility and scoring algorithm, confirming that that code works with arrays of coordinates.
> SCHED-680: Complete proper motion calculations

- scheduler/core/programprovider/ocs/ocsprogramprovider.py
- tests/unit/scheduler/core/collector/test_proper_motion.py
- tests/unit/scheduler/services/horizons/test_horizons_client.py
This will be looked up using JPL/Horizons. It requires this lucupy update to work:
https://github.com/gemini-hlsw/lucupy/pull/102
> SCHED-683: Remove RA and dec from NonsiderealTarget

- scheduler/core/calculations/nightevents.py
Change nightevents utc and local time lists to be created from scratch using pandas
> Improve timing in collector nightevents

- scheduler/services/visibility/snapshot.py
Changed visibility data format to store data ranges in Redis instead of big lists.
Please be careful, this change may break things if Redis cache is not removed, since it is not compatible with the old format.
This change improves the timing in the schedule visibility calculation when using Redis data for the default parameters (semester visibility true and start date Oct 1, 2018) going from aprox 2 minutes to 1.5 minutes. Also the amount of stored data decreases to about a quarter of the original size.
Tests will fail if the Redis cache is not cleaned.
> GSCHED-710 modified visibility slot idx format

- scheduler/graphql_mid/schema.py
- scheduler/graphql_mid/types.py
Strawberry default error handling was not working, since the websocket connection was killed and was not reconnecting, because a strange server state.
If the server is killed and restarted, the UI reconnects the socket correctly, but if an error kills the server, it is not able to comeback, then it seems better to catch the server exceptions and send them to the UI using union types.
> Added union types to handle subscription errors

- scheduler/services/visibility/calculator.py
Otherwise TimeDelta assumes a default format of 'jd', which will not match the value and visibility fraction factor in observation scores will be wrong.
This fix has not been tested because the calculated values have been used to fill the redis database, which I can't alter.  My understanding is that the redis database must be refilled using this fix.  Then we may have the observation scores calculated correctly.
> Fix visibility_time format to match its value (both in seconds).

- scheduler/core/programprovider/ocs/ocsprogramprovider.py
As with, parse_time_allocation, add a band parameter to parse_time_used to make the results equivalent to those for GPP. This is so that future changes to GreedyMax to support used time by band will continue to work for the OCS validation mode.
This requires the lucupy changes in https://github.com/gemini-hlsw/lucupy/pull/116
> Add band to time_used

- scheduler/config.yaml
- scheduler/core/builder/schedulerbuilder.py
- scheduler/core/builder/validationbuilder.py
- scheduler/core/components/collector/collector.py
- scheduler/engine/engine.py
- scheduler/services/redis_client/redis_client.py
- scheduler/services/visibility/calculator.py
- tests/unit/conftest.py
In the `config.yaml` file the parameter `with_redis` will be found and can be used to disable redis.
The visibility calculations are done in the collector and just for the programs needed in the requested plan, which is different from the information retrieved from Redis that stores a full list of programsfor the semester, calculatiing the full list locally at startup means a huge overhead.
> Enabled with_redis boolean

- scheduler/services/visibility/calculator.py
`has_resources` variable depends on the instrument, only for GMOS all resources are used.
if `has_resources` is false, the script should not keep calculating stuff, just set the visibility to an empty array immediately.
Same idea if `can_schedule` is false.
> Filter all resources only if the instrument is GMOS

- scheduler/core/components/optimizer/greedymax.py
- scheduler/core/components/selector/selector.py
- scheduler/core/output/__init__.py
- scheduler/scripts/hours_up.py
These fixes should allow us to run the scheduler on an arbitrary integer minute time grid. It's been tested using 5 minute time slots.  To change this in Heroku we need to update time_slot_length in config.yaml and then repopulate the redis cache.
> Coarse time grid bug fixes

- scheduler/core/components/collector/collector.py
Set the observation status to ONGOING if is not complete (has been split).
> Minor fix to setting observation status during time accounting

- scheduler/core/components/ranker/base.py
- scheduler/core/components/ranker/default.py
- scheduler/core/components/selector/selector.py
Adds a new factor to increase the score for ongoing observations.
Fixes a bug that improves the ranker performance. The ranker is currently instantiated in engine.build, making ranker.night_indices include all the nights to schedule. Therefore, the ranker was looping over all those nights every time it was called. I added a night_indices parameter to ranker.score_observation so that it would only score the one night being treated by the selector. The ranker instantiation is the same so that the arrays are zeroed and the metric_score is defined for later use. There may be a better way to do this but it was simple and it works. We can do more fundamental refactoring for real-time mode.
> GSCHED-833: ongoing score boost, ranker night_indices bug fix
