gemini-hlsw/scheduler

README.md
environment.yml

Quick add for the environment file discussed with Bryan

SCHED-26: add environment.yml 

---

.gitignore
greedy_max/__init__.py
resource_mock/__init__.py

This PR mirrors #8 but in the new implementation merge in #7.

SCHED-31: Add ask_input flag, .gitignore

---

resource_mock/__init__.py

The date selected from the tables must be equal to or the closest that is earlier than the requested date.

Added _previous

---

README.md

Added other necessary dependencies.

Added dependencies.

---

collector/__init__.py
collector/program.py
collector/xmlutils.py
common/structures/conditions.py
common/structures/execution_status.py
common/structures/observation_status.py
common/structures/phase2_status.py
selector/__init__.py

More cleanup, error elimination, and types added. Redundant code removed and simplified, and Python standards implemented.

SCHED-44: Cleanup part 3

---

collector/__init__.py

get_obs_class yields a list of all observation classes for the observes in an observations. This adds a select_obsclass function that uses this list to set the obsclass for the observation has a whole based on the precedence of the classes.

Add select_obsclass to select obsclass based on precedence

---

common/minimodel/__init__.py
common/structures/conditions.py

Initial implementation of the mini-model, minus output and some internal data structures. (Will add these tomorrow.)

SCHED-71: Initial mini-model implementation.

---

process_manager/main.py
process_manager/manager.py
process_manager/process.py
process_manager/runner.py
process_manager/scheduler.py
process_manager/task.py

This work independently from the rest of the code. A first approach to the process manager for both standard and realtime uses.

Sched 74: Process manager new structure

---

common/minimodel/__init__.py

Removed warnings and made some bugfixes to dataclasses, as well as added some value checking.

SCHED-71: Mini model updates and bugfixes

---

common/minimodel/__init__.py

Some small tweaks to the mini-model to simplify things for the Collector and to include some missing data.

SCHED-71: Mini-model tweaking.

---

common/api/__init__.py

Just added a quick comment about how exceptions should be handled in the API.

SCHED-73: Added comment.

---

common/minimodel/__init__.py

AND groups (`AndGroup`) now explicitly require `num_to_observe` to be EQUAL to the length of its children.
OR groups (`OrGroup`) now explicitly require `num_to_observe` to be LESS THAN the length of its children.
Both groups no longer allow for `num_to_observe` to be 0.

SCHED-71: Mini model AND OR group refinements.

---

common/minimodel/__init__.py

No idea how I managed to get this into the code base, but fixing it now.

SCHED-71: Undoing weird commit.

---

odb_extractor_atoms.py

Here is a new version with the following changes:
- can process an entire program at once, working down through the groups and observations to define atoms (prog_proc)
- calculates obsclass and qastate for each atom and propagates up to observation. These should agree with the values from the ODB given at the observation level. This won't be exact yet. A QA state of 'NONE' means not observed.
This is meant to help me review the results of the atom algorithm more broadly and it shows how atom properties are calculated from the included sequence steps and the propagated to the observation level.
This currently works on the observations without much selection or other modification. For the validation mode we will want to 'unobserve' most of the executed observation (e.g. unset qastates) and …

Add program processing, class/qastates for atoms

---

api/ocs/__init__.py
api/ocs/ocs_keys.py
provider.py

Moves most of the logic from `test_provider.py` to api.ocs module and fixes the Enums used for store the JSON keys.

SCHED-80: OCSProgramProvider

---

common/minimodel/__init__.py

I have no idea how I managed to screw up this PR.

SCHED-80: Adding coordinate centers to SiteInformation.

---

api/abstract/__init__.py
api/ocs/__init__.py
common/minimodel/__init__.py
test_ocs_program_provider.py

This simple PR:
1. Updates the docstrings to provide more thorough and complete information;
2. Cleans up and adds some more exception handling;
3. Removes an unnecessary method from `OcsProgramProvider`;
4. Hooks up and fixes the logic in the `OcsProgramProvider._check_too_type` method; and
3. Marks some TODOs that may require or merit modification as the refactoring continues.

SCHED-84: Update docstrings for mini-model and API.

---

common/minimodel/__init__.py

We will now represent instruments and instrument configurations simply as a set of `Resource` objects.

SCHED-72: Removal of InstrumentConfiguration from the model.

---

api/ocs/__init__.py

This fixes an error that was caused by SCHED-82 and makes the API more explicit.

SCHED-89: Fixed issue in API and made keywords explicit.

---

api/abstract/__init__.py
api/ocs/__init__.py
common/minimodel/__init__.py
tests/test_ocs_api.py

Conditions are now also comparable using standard comparison operators to determine if one set of conditions satisfies another.

SCHED-90: Separated Conditions out of Constraints.

---

api/abstract/__init__.py
api/ocs/__init__.py
common/minimodel/__init__.py
tests/test_ocs_api.py

This PR comprises:
1. Fixes to the mini-model.
2. Fixes to the OCS API and some small changes to the API interface.
3. Completion of the basic test case for reading in a program.

SCHED-85: Mini-model / OCS API test case and bugfixes

---

collector/__init__.py
common/minimodel/__init__.py

SCHED-75: Fixing imports.

---

api/ocs/__init__.py
common/minimodel/__init__.py
tests/test_ocs_api.py

While running the test cases, which were suddenly failing, I found a bug in the way that observations were collected in the mini-model, and in how wavelengths were handled in general.

SCHED-98: Fixing test cases and bug in mini-model and API.

---

scripts/download_programs.py

Directory changes and fixes to remove `tmp` directory used in downloads.
No longer any need to specify tmp directory: automatically creates it.

SCHED-104: Small fixes to download script.

---

README.md
collector/__init__.py
common/output/__init__.py
environment.yml
scripts/run_collector.py

There was an error in how the `obs_classes` were maintained in the original PR.
In addition, this PR contains some efficiency improvements (proper motion fixed numpy arrrays are now moved into pre-collection, and the code had been made much more simple.)

SCHED-106: Multiple fixes

---

api/ocs/__init__.py
common/minimodel/__init__.py
common/output/__init__.py
environment.yml
scripts/export_atoms.py
scripts/run_collector.py

Update to our OCS Provider from the changes at the script #62

SCHED-93: Atom creation update

---

collector/test/test_proper_motion.py
components/collector/__init__.py
components/collector/test/test_proper_motion.py

New approach based on Bryan's approach: 
https://gist.github.com/bryanmiller/09202047fba8697be9af43735fc4a87c
Test needs a review on precision to pass correctly

Sched 114: Proper Motion for sidereal Targets

---

.github/workflows/pytest.yml
environment.yml

SCHED-105: Add Coverage for testing

---

components/ranker/__init__.py
scripts/run_scheduler.py

This fixes a bug in the Ranker where numpy was being used incorrectly.
The Selector now runs to completion.

SCHED-119: Finally found bug.

---

common/sky/altitude.py
common/sky/brightness.py
common/sky/constants.py
common/sky/events.py
common/sky/moon.py
common/sky/sun.py
common/sky/test/fixtures.py
common/sky/test/test_events.py
common/sky/utils.py
components/collector/__init__.py
components/selector/__init__.py
scripts/run_scheduler.py

This fixes some minor bugs, eliminates almost all warnings, and provides instructions on how to access the various data objects populated by the `Collector` and the `Selector`.

SCHED-123: Various bugfixes and cleanup, instructions for accessing data

---

api/observatory/gemini/__init__.py
api/programprovider/ocs/__init__.py
common/decorators/__init_.py
common/decorators/__init__.py
common/minimodel/__init__.py

An implementation on how we can handling special cases to structures on the minimodel without modifying the base structures. This could be extended to handle more telescopes.

Sched 95: Special Handling Cases

---

common/calculations/nightevents.py
common/minimodel/site.py
components/collector/__init__.py
components/nighteventsmanager/__init__.py
components/ranker/__init__.py
horizons/__init__.py

This changes the way `Site` is implemented as an `Enum` so that it works with pickling, which is required for process management.
It also simplifies the code since we no longer have to access fields via `site.value.fieldname` and can now just access them as `site.fieldname`. The changes have been made through the code base and the test cases appear to pass.

SCHED-145: Redesign of Site and modifications to make it work properly.

---

environment.yml

Las changes broke the env for the CI, this should fix it

HOTFIX: Fix environment.yml to work with pip dependencies

---

mock/environment/__init__.py

The commented code is my current work on the weather data dictionary

SCHED-169: Made Env into a proper class

---

common/output/__init__.py
components/optimizer/__init__.py
components/optimizer/base.py
components/optimizer/dummy.py
scripts/weather_experiment.py

Fixing the ugly `import ... __init__` code.

SCHED-133: Got rid of import horrors.

---

mock/environment/__init__.py
scripts/weather_experiment.py

Code looks good. One error:
-  First minute missing in nights after first night.
- Also, look at simplification of night processing code loops.
This adds some temporary testing code that will be removed after the above are fixed and makes a couple minor changes.

SCHED-179: Testing.

---

mock/environment/__init__.py
scripts/weather_experiment.py

Last day was not being added as loop terminated before date transition detected.
Also cleaned up a few things and added a message about CC and IQ processing and added wind speed and direction processing.
Put columns back as pandas, when presented with a row with a timestamp and all other columns null, mangled the timestamp when making a dataframe.

SCHED-179: Fixing bugs in Env processing.

---

common/minimodel/constraints.py
components/selector/__init__.py
mock/environment/__init__.py

Removed `WV` and `wind_sep` from `Variant` and adjusted `Selector` to account for these.
`wind_sep` is now fixed to 40 degrees.

SCHED-183: Fixed Variant.

---

mock/environment/__init__.py

Also added forceable reprocessing and cleaned up imports.

SCHED-185: Fixed default values for windspeed and winddir

---

app/process_manager/manager.py
common/meta/__init__.py
graphql_server/__init__.py

Adds Singleton class for all our singletons! (ProcessManager y PlanManager)

SCHED-196: Modifies Process Manager

---

services/environment/__init__.py

Moving files broke the Env service, and did some basic cleanup.

SCHED-201: Fixed path bugs and cleaned up.

---

app/components/collector/__init__.py
services/environment/__init__.py

This PR does two primary things:
1. In the historical environmental data, measurements are typically taken every minute during the night when the telescope is active. There are, however, periods of one or more minutes where weather measurements were not taken. In these cases, fill in the gaps with copies of the previous row with the time adjusted.
2. Add a `time_slot_length` (in minutes) to the query so that we can request longer time slot lengths when doing e.g. simulations that span a long period of time and we want to work with longer time slot lengths as one minute intervals results in too many time slots. Then for each night, the entries `start_time + x * time_slot_length` for all `x >= 0` that are in the time range specified to the query will be returned. A default length of 1 …

SCHED-203: Env service improvements

---

app/core/scheduler/scheduler.py
app/graphql/schema.py
main.py
planmanager.py
scripts/run_scheduler.py

An attempt at a fix to move `PlanManager` to its own module and not be of metaclass `Singleton` to see if this solves an `asyncio` issue.

SCHED-209: PlanManager fix.

---

.github/workflows/deploy.yml

Automatically pushed new version to Heroku when pushed to main.

SCHED-218: Add deploy github action

---

app/core/output/__init__.py
app/core/scheduler/scheduler.py
scripts/export_atoms.py
scripts/run_scheduler.py

Some bugfixes for the Scheduler due to changes to lucupy as to how programs are printed and to make the change to the use of frozensets instead of sets.

SCHED-242: Fixing errors in printing and warnings with not using frozenset.

---

app/core/builder/blueprint.py
app/core/components/selector/__init__.py
app/core/programprovider/ocs/__init__.py
app/core/scheduler/modes.py
config.yaml

Sched 257: Add sources to config 

---

app/core/builder/blueprint.py
app/core/components/selector/__init__.py
app/core/programprovider/ocs/__init__.py
app/core/scheduler/modes.py
config.yaml

Reverts gemini-hlsw/scheduler#188

Revert "Sched 257: Add sources to config "

---

app/core/builder/blueprint.py
app/core/components/selector/__init__.py
app/core/programprovider/ocs/__init__.py
app/core/scheduler/modes.py
config.yaml

Reverts gemini-hlsw/scheduler#191
Readding as this does not appear to fix the problem.

Revert "Revert "Sched 257: Add sources to config ""

---

app/core/calculations/groupinfo.py
app/core/components/selector/__init__.py

This PR might be unmerged or changed.

SCHED-276: Added program_id to GroupData.

---

app/core/calculations/groupinfo.py
app/core/components/selector/__init__.py

Reverts gemini-hlsw/scheduler#202
We will put this in the mini-model instead.

Revert "SCHED-276: Added program_id to GroupData."

---

app/core/components/selector/__init__.py

SCHED-278 had some severe performance issues that would have probably caused a bottleneck in the algorithm. Doing tests, the time required for each program is from approximately 50% to 95%.

SCHED-279: Optimization for Selector._get_top_level_groups.

---

app/core/components/optimizer/__init__.py
app/core/components/optimizer/dummy.py
app/core/components/optimizer/greedymax.py
app/core/components/ranker/default.py
app/core/plans/__init__.py

This is based on the dummy optimizer and does not yet handle groups, atoms, or use the visibilities for placing observation. It fixes a few bugs in the dummy optimizer. It does not split, to fill in a night it iterates over observations in order of decreasing score until it finds something to schedule in the remaining time.

GreedyMax refactoring - step 2

---

app/core/builder/builder.py
app/core/calculations/groupinfo.py
app/core/calculations/nightevents.py
app/core/calculations/programinfo.py
app/core/calculations/scores.py
app/core/calculations/selection.py
app/core/calculations/targetinfo.py
app/core/components/collector/__init__.py
app/core/components/optimizer/base.py
app/core/components/optimizer/dummy.py
app/core/components/ranker/default.py
app/core/components/selector/__init__.py
app/core/programprovider/ocs/__init__.py
app/core/programprovider/ocs/test/test_ocs_filtering.py
app/core/scheduler/modes.py
app/core/scheduler/scheduler.py
app/graphql/scalars.py
app/graphql/schema.py
app/graphql/server.py
mock/environment/__init__.py
mock/resource/__init__.py
requirements.txt
scripts/check_headers.py
scripts/download_programs.py
services/horizons/__init__.py
services/horizons/test/test_horizons_client.py

This is the partner PR of SCHED-270 in the lucupy project:
https://github.com/gemini-hlsw/lucupy/pull/27
It performs deep copies of structures returned in the `Selection` so that they can be modified for time accounting and will not alter the original data structures.

SCHED-270: deepcopy of structures used in Selection

---

scheduler/scripts/filter_demo.py
scheduler/services/resource/filters.py

This PR:
1. Fixes a bug in one of the filters.
2. Makes the `CompositeFilter` easier to use by providing default values.
3. Adds a `filter_demo.py` file to the scripts directory for QA testing or as an example of how filters work.

SCHED-328: Fixed bug in filters and added script for filter demo.

---

scheduler/core/builder/blueprint.py
scheduler/core/builder/builder.py
scheduler/core/components/optimizer/__init__.py
scheduler/core/components/optimizer/base.py
scheduler/core/components/optimizer/greedymax.py
scheduler/core/components/optimizer/timeline.py
scheduler/scripts/run_greedymax.py

Greedy-max changes due to rebase.

Gmax refactor

---

scheduler/core/calculations/selection.py
scheduler/core/components/optimizer/__init__.py
scheduler/core/components/optimizer/base.py
scheduler/core/components/optimizer/dummy.py
scheduler/core/components/selector/__init__.py
scheduler/services/resource/night_resource_configuration.py
scheduler/services/resource/ocs_resource_service.py

This simplifies data access for GreedyMax.

SCHED-333: Simplifications for data.

---

scheduler/core/components/collector/__init__.py
scheduler/core/components/optimizer/dummy.py
scheduler/core/components/optimizer/greedymax.py
scheduler/core/plans/__init__.py
scheduler/core/programprovider/ocs/__init__.py
scheduler/core/service/service.py
scheduler/graphql_mid/schema.py
scheduler/graphql_mid/types.py
scheduler/scripts/run_scheduler.py

Add NightStats: a compilation of different information that it would be display in the UI.
And Plans summary: a summary by program of all nights that would also be display in the UI
This adds modifications to the Optimizer that later would need to be reconcile after GreedyMax work is completed. Probably a Dummy refactory would be in place to use common logic.

SCHED-303: Add Night Stats and Plans Summary

---

scheduler/core/components/collector/__init__.py
scheduler/core/components/selector/__init__.py
scheduler/core/service/service.py
scheduler/db/planmanager.py
scheduler/graphql_mid/schema.py
scheduler/graphql_mid/types.py
tests/unit/scheduler/graphql_mid/test_graphql_queries.py

And add sites as parameter to work with schedule query

SCHED-341: Fix filtering obs by site in collector 

---

scheduler/core/calculations/scores.py
scheduler/core/calculations/selection.py
scheduler/core/components/optimizer/base.py
scheduler/core/components/optimizer/dummy.py
scheduler/core/components/optimizer/greedymax.py
scheduler/core/components/optimizer/test_greedymax.py
scheduler/core/components/optimizer/timeline.py
scheduler/core/components/ranker/base.py
scheduler/core/components/selector/__init__.py
scheduler/core/plans/__init__.py
scheduler/scripts/run_scheduler.py

This is a cleanup and type addition of GM, along with an initial test case.
There will likely be a second PR with more test cases.

SCHED-340: GreedyMax first pass

---

scheduler/core/calculations/programinfo.py
scheduler/core/calculations/selection.py
scheduler/core/components/optimizer/dummy.py
scheduler/core/components/optimizer/greedymax.py
scheduler/core/components/optimizer/timeline.py
scheduler/core/components/ranker/default.py
scheduler/core/components/selector/__init__.py
scheduler/core/plans/__init__.py
scheduler/core/programprovider/ocs/__init__.py
scheduler/db/dbmanager.py
scheduler/graphql_mid/inputs.py
scheduler/graphql_mid/scalars.py
scheduler/graphql_mid/schema.py
scheduler/graphql_mid/types.py
scheduler/scripts/filter_demo.py
tests/unit/scheduler/core/programprovider/ocs/test_ocs_api.py
tests/unit/scheduler/graphql_mid/test_graphql_mutations.py
tests/unit/scheduler/graphql_mid/test_graphql_queries.py

Cleanup of code and change to use of the ______ID classes.
WIP: This is not to be merged yet.

SCHED-361: Implementation of IDs in Scheduler and cleanup

---

scheduler/app.py

... so we can query from the UI.

SCHED-366: Add UI to origins

---

scheduler/app.py

Reverts gemini-hlsw/scheduler#254

Revert "SCHED-366: Add UI to origins"

---

scheduler/core/components/optimizer/greedymax.py
scheduler/core/output/__init__.py

Rescore programs after a group is included in a plan. Only incomplete groups have their scores updates, leaving the scores of the groups in the plans as they were when selected.

SCHED-353: Program rescoring

---

scheduler/services/resource/ocs_resource_service.py

There were some issues in `OcsResourceServices`:
1. Using `date` (a type) as a variable name.
2. Conversion of single items into `FrozenSet`.
3. Type information for `EngTask` and `Fault` should be `Set`.
In the last case, this would be better as `FrozenSet`, but at this point, the conversion would be difficult.

SCHED-378: Fixing OcsResourceService issues.

---

requirements.txt
scheduler/core/builder/blueprint.py
scheduler/core/components/selector/__init__.py
scheduler/core/sources.py
scheduler/scripts/run_greedymax.py
scheduler/services/environment/__init__.py
scheduler/services/environment/ocs_env_service.py
scheduler/services/logger_factory/__init__.py
scheduler/services/resource/night_resource_configuration.py

`OcsEnvService` appears to work.

SCHED-365B: Migration of changes due to rebase issues.

---

scheduler/core/components/optimizer/greedymax.py
scheduler/core/components/optimizer/timeline.py

Add observation splitting (at atoms) and telluric calibration selection.

Gmax refactoring - finish SCHED-354/355

---

scheduler/core/components/optimizer/greedymax.py

Fix a likely bug that would prevent the placement of a 2nd standard. Needs testing to confirm. Does not change the results otherwise.

Fixes a likely bug in standards placement

---

scheduler/core/components/collector/__init__.py
scheduler/core/components/optimizer/greedymax.py
scheduler/core/output/__init__.py

Fixed index-related bugs in GreedyMax and the collector time accounting.
Also, added atom start/end to print_plans for debugging.

Fixed bugs related to atoms and observation splitting

---

scheduler/core/programprovider/ocs/__init__.py

Parse notes while traversing the observation tree to look for text indicting that observations should not be split. The note is assumed to apply to all observations at or below its level (program, group, observation). The atom generation then uses this information. Tested with GS-2018B-Q-108-18.
I also fixed bugs related to note parsing for FT scheduling info (all top-level notes need to be searched) and to atom generation.

Add note parsing for 'do not split' info, bugfixes

---

scheduler/core/components/optimizer/greedymax.py
scheduler/core/programprovider/ocs/__init__.py
scheduler/services/resource/base.py

Setting and use of obs_mode by GreedyMax
atom bugfixes
add MOS mask barcodes to resources, so the selector should now select a MOS observation only if the MOS mask is in the instrument.
Requires the following PR
https://github.com/gemini-hlsw/lucupy/pull/60

Fix setting observing mode from atom configs

---

scheduler/core/__init__.py
scheduler/core/statscalculator/__init__.py
scheduler/graphql_mid/types.py
scheduler/services/chronicle/data/cleanup.py

* Add copyright header
* Use `Counter[Band]` instead of `Dict[Band, int]`
* `sum` over generator comprehension instead of `for` loop
* PyCharm did some spacing formatting
* Isolated running code to main for chronicle, which we will be changing anyway

Slight modifications: copyright and couple changes to stats calcs

---

scheduler/core/components/collector/__init__.py

The previous modifications to time accounting assumed there were no gaps in the plan. By using instead the start time slot of each visit, this is fixed to account for gaps.

SCHED-491B: Small bugfix regarding start times.

---

demo/try_scheduler.ipynb
scheduler/core/components/ranker/default.py

This PR fixes two things in Validation mode:
1. Changes the upper limit on number of nights to schedule and number nights of visibility calcs from 10 to 365.
2. Updates the code base to work with Py3.11.

SCHED-507: Fixed upper limit of 10 on number boxes.

---

scheduler/core/programprovider/ocs/__init__.py
tests/unit/scheduler/core/programprovider/ocs/test_ocs_api.py

Some changes to functions and parameters to simplify the time utils in lucupy.

SCHED-359: Accommodate changes to lucupy. MUST UPDATE LUCUPY.

---

scheduler/core/eventsqueue/event_queue.py
scheduler/core/eventsqueue/events.py
scheduler/core/eventsqueue/nightchanges.py
scheduler/core/output/__init__.py
scheduler/core/service/service.py
scheduler/graphql_mid/types.py
scheduler/scripts/check_headers.py
scheduler/scripts/run_main.py
tests/__init__.py
tests/unit/__init__.py
tests/unit/scheduler/__init__.py
tests/unit/scheduler/core/__init__.py
tests/unit/scheduler/core/collector/__init__.py
tests/unit/scheduler/core/collector/collector_fixture.py
tests/unit/scheduler/core/collector/test_datetime_conversions.py
tests/unit/scheduler/core/collector/test_proper_motion.py
tests/unit/scheduler/core/programprovider/__init__.py
tests/unit/scheduler/core/programprovider/ocs/__init__.py
tests/unit/scheduler/core/programprovider/ocs/test_ocs_api.py
tests/unit/scheduler/core/programprovider/ocs/test_ocs_filtering.py
tests/unit/scheduler/core/service/__init__.py
tests/unit/scheduler/core/service/test_clear_observation_info.py
tests/unit/scheduler/graphql_mid/__init__.py
tests/unit/scheduler/graphql_mid/test_graphql_mutations.py
tests/unit/scheduler/graphql_mid/test_graphql_queries.py
tests/unit/scheduler/services/__init__.py
tests/unit/scheduler/services/horizons/__init__.py
tests/unit/scheduler/services/horizons/test_horizons_client.py
tests/unit/scheduler/services/resource/test_ocs_resource_service.py

This also removes the blockage code, as detailed in GSCHED-558, assigns a UUID to each event, and links `InterruptionEvent`s with `InterruptionResolutionEvent`s, making sure that the link is valid between types.

SCHED-555: Modify event hierarchy for time loss and fix affected files.

---

scheduler/core/builder/operationsbuilder.py
scheduler/core/builder/schedulerbuilder.py
scheduler/core/builder/validationbuilder.py
scheduler/core/eventsqueue/events.py
scheduler/core/sources.py
scheduler/graphql_mid/schema.py
scheduler/services/resource/base.py
scheduler/services/resource/google_drive_downloader.py
scheduler/services/resource/ocs_resource_service.py

This code parses faults and engineering tasks.
I have checked manually at it appears that (finally) all the `twi` entries in engineering tasks are properly loaded.
It also fixes an issue where the calendar was being loaded twice (once for each site, which was extraneous).

GSCHED-560: Parsers for faults and engineering tasks

---

definitions.py
scheduler/core/calculations/nightevents.py
scheduler/core/components/collector/__init__.py
scheduler/scripts/run_greedymax.py
scheduler/scripts/run_with_events.py
scheduler/services/resource/base.py
scheduler/services/resource/ocs_resource_service.py

Now instrument data is loaded on a site-by-site basis. This fixes the problems of:
1. Instrument data being loaded twice.
2. Instrument data needing to be loaded separate from the other file data.
Remaining issue: instrument data comes from a Google sheets file. Can we work this to get `Union[str, BytesIO]` like with other types?

SCHED-566: Instrument calendar now loads per site.

---

scheduler/core/components/selector/__init__.py

See https://noirlab.atlassian.net/jira/software/c/projects/GSCHED/boards/62?selectedIssue=GSCHED-571 for a list of the rules for program exclusions.

SCHED-571: Filter programs.

---

scheduler/core/sources.py
scheduler/services/resource/__init__.py
scheduler/services/resource/data/README.md
scheduler/services/resource/event_generators.py
scheduler/services/resource/file_based_resource_service.py
scheduler/services/resource/file_resource_service.py
scheduler/services/resource/filters.py
scheduler/services/resource/google_drive_downloader.py
scheduler/services/resource/night_configuration.py
scheduler/services/resource/ocs_resource_service.py
scheduler/services/resource/resource_service.py

This has been driving me crazy for awhile. It was cluttered, difficult to navigate, and impossible to find things.

SCHED-572: Major cleanup of resource package.

---

scheduler/core/components/collector/__init__.py

The visibility calculation now considers whether the required resources are available. The implementation works for validation mode, but it will probably require some refactoring for real-time mode.

Include resource availability in visibility calculations

---

scheduler/services/resource/file_based_resource_service.py

Now that we are using `zoneinfo`, `datetime` objects should be timezone-aware.
Previously, to get the time zones correct (using `pytz`) for `Fault`s and `EngineeringTask`s, we had to jump through hoops of adding and dropping time zone information. Now we can simply replace timezone information in timezone-naïve `datetime`s with the correct `ZoneInfo` object.

SCHED-598: Fixing timezone info for engineering tasks and fault reports.

---

scheduler/core/components/collector/collector.py
scheduler/services/resource/file_based_resource_service.py
scheduler/services/resource/resource_service.py

Add lost changes from GSCHED-440 (using resource availability for visibility calculations)
Write resource description and type attributes.
Fix typo in GMOS 1.5 arcsec FPU name.
Dependent on https://github.com/gemini-hlsw/lucupy/pull/80

GSCHED-607: use resources for visibility calcs, write resource description/type

---

scheduler/core/components/optimizer/greedymax.py

GreedyMax tries to avoid small gaps in plans by shifting observations that are near the boundary of a time interval to the edge.  It was using the wrong scores at the boundary edges so groups were getting shifted incorrectly.  This fixes that and a problem with airmass plots (night_idx must be supplied).

Fix GreedyMax group placement bug

---

.github/workflows/deploy.yml
.github/workflows/production.yml
.github/workflows/pytest.yml

SCHED-591: Add production workflow

---

scheduler/core/components/ranker/default.py

Implementing best practices for `dataclass` `RankerParameters`.

SCHED-650: Cleanup for original SCHED-650 PR and RankerParameters.

---

scheduler/core/components/collector/collector.py

Accidentally slipped an error into the `Collector` when making the changes for `GSCHED-674` and `GSCHED-675`.

SCHED-677: Fixing error in Collector.

---

scheduler/core/components/ranker/default.py
scheduler/core/programprovider/ocs/ocsprogramprovider.py

This PR is behaving strangely:
https://github.com/gemini-hlsw/scheduler/pull/442
It does not appear to be able to be merged. This a fresh PR just migrating the changes over.

SCHED-656:  Retrying merge of Bryan's PR.

---

scheduler/core/programprovider/abstract/programprovider.py
scheduler/core/programprovider/ocs/ocsprogramprovider.py

Bug fixes and new capabilities for OCS atom parsing. More documentation is here
https://docs.google.com/document/d/165y0Myjh0Il1o31zVzQESvJhL32BwqAre8XCd8OYCL8/edit

GSCHED-474: atom parsing improvements

---

scheduler/core/calculations/targetinfo.py
scheduler/core/components/collector/collector.py
scheduler/services/horizons/horizons_client.py
scheduler/services/visibility/calculator.py

I added various missing class and variable definitions so that it would run without crashing. More tests are needed that the nonsidereal calculations are correct.

Gsched 627: bug fixes

---

scheduler/scripts/gpp_api_tests.py
scheduler/scripts/gpp_atoms.py

This adds some scripts with initial tests of the GPP API using Andy's pyexplore client. https://github.com/andrewwstephens/pyexplore

Initial GPP API tests using pyexplore

---

scheduler/core/programprovider/gpp/__init__.py
scheduler/core/programprovider/gpp/gppprogramprovider.py
scheduler/scripts/gpp_atoms.py

Started creating GppProgramProvider with a parallel organization to the OcsProgramProvider. Atom parsing from a GPP query can be tested with the gpp_atoms.py script.

GSCHED-701: start on GppProgramProvider, atom parsing

---

scheduler/routes.py

Fixed asyncio needed thread

---

scheduler/core/components/ranker/base.py
scheduler/core/components/ranker/default.py
scheduler/core/components/selector/selector.py
scheduler/core/programprovider/abstract/programprovider.py
scheduler/core/programprovider/gpp/gppprogramprovider.py
scheduler/core/programprovider/ocs/ocsprogramprovider.py
scheduler/scripts/gpp_programs.py

This is a first implementation of filling the scheduler minimodel using GPP data queried with pyexplore.
It uses classes common with OCS and is dependent on
https://github.com/gemini-hlsw/lucupy/pull/105

GSCHED-702: fill minimodel with GPP data

---

.github/workflows/deploy.yml

Missed the PAT to download at the moment of creating the container.

SCHED-717: Missing env in deploy.yml

---

scheduler/core/statscalculator/statscalculator.py

Timeloss sum is complaining about format

Fixed time_loss int - datetime.timedelta sum error

---

scheduler/graphql_mid/types.py

Send JSON object instead JSON string

---

.github/workflows/deploy.yml
Dockerfile
scheduler/app.py
scheduler/graphql_mid/schema.py

Added APP_VERSION gotten from environment variables in the compiled docker image.

Gsched 762 add version

---

requirements.txt
scheduler/core/components/collector/collector.py
scheduler/core/programprovider/gpp/gppprogramprovider.py
scheduler/scripts/gpp_api_tests.py
scheduler/scripts/gpp_atoms.py
scheduler/scripts/gpp_observations.py
scheduler/scripts/gpp_programs.py

Removed pyexplore, commented pyexplore dependency until it gets replaced with new API or direct queries.

Remove pyexplore

---

scheduler/app.py
scheduler/scripts/fill_redis.py
scheduler/services/redis_client/__init__.py
scheduler/services/visibility/calculator.py

`visibility_calculator` can be called with parameters `with_redis` and `programs_ids` if desired, otherwise everything will work as it was before this change.

Enabled with_redis functionality

---

scheduler/core/programprovider/ocs/ocsprogramprovider.py
scheduler/services/resource/filters.py

All instruments will have the parsed fpu, filters and dispersers in its resources.
If the instrument is not GMOS, the new resources (fpu, filters and dispersers) are not considered as required.

Added instrument resources

---

scheduler/core/components/ranker/default.py
scheduler/core/eventsqueue/nightchanges.py
scheduler/core/programprovider/ocs/ocsprogramprovider.py
scheduler/core/statscalculator/statscalculator.py
scheduler/scripts/run.py
scheduler/services/resource/file_based_resource_service.py

These changes are mostly related to generalizing for future GPP integration
- ranker/default.py (band from obs rather than program)
- ocsprogramprovider (cleanup)
- statscalculator.py (band from obs rather than program)
- file_based_resource_service.py (ignore commented lines in file)
- run.py (ignore commented lines in file, add example for plan output to file)
- nightchanges.py (added option to NightlyTimeline.display() to output to an optional text file for simple checks on output)

Small changes for GPP generalization

---

scheduler/core/calculations/groupinfo.py
scheduler/core/components/optimizer/greedymax.py
scheduler/core/components/ranker/base.py
scheduler/core/components/ranker/default.py
scheduler/core/components/selector/selector.py
scheduler/core/events/queue/nightchanges.py
scheduler/core/plans/plan.py
scheduler/core/plans/visit.py
scheduler/core/statscalculator/statscalculator.py
scheduler/engine/engine.py
scheduler/services/resource/file_based_resource_service.py

Again, sorry for the two-in-one PR but the code was really mixed between both issues. 
Specific event nights are not showing the correct time losses, so I will add a new task just for that because is not that straightforward. 
I run the metrics with Kristin and told me she need to test it more so future issues might arise.

GSCHED-788 and GSCHED-804: Modify metrics and fix time losses

---

scheduler/core/events/cycle/cycle.py
scheduler/engine/engine.py
tests/unit/scheduler/core/events/cycle/test_event_cycle.py

Also added a log for the user to know the plan calculation has ended and the total time it took to be calculated

GSCHED-836: Change event cycle to loop through events
